/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_mynative_ConNetJni */

#ifndef _Included_com_example_myapplication_mynative_ConNetJni
#define _Included_com_example_myapplication_mynative_ConNetJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_mynative_ConNetJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_mynative_ConNetJni_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myapplication_mynative_ConNetJni
 * Method:    getHexSixteen
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_mynative_ConNetJni_getHexSixteen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_myapplication_mynative_ConNetJni
 * Method:    getcdHexDecimal
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_mynative_ConNetJni_getcdHexDecimal
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
